### ISSUE TITLE
OSError: [Errno 1] Operation not permitted  in Mac  

### ISSUE THREAD

**Issue by yuyilei** [Humbertzhang/Judgement#1]
I use Mac, when I "python judgement.py" , it shows  " os.mknod("testByJudgement/test.py")
OSError: [Errno 1] Operation not permitted " , I guess there are some troubles in permission.

**Comment by maxkezhang** [comment]
Well, I use `open(filename, "w+")` to avoid the permission question now.
Thank you for your issue.
